import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | Smart Music Lab',
  description: 'Terms of Service for Smart Music Lab - AI Personalized Song Generator',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-base-200">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="bg-base-100 rounded-2xl shadow-xl p-8 md:p-12 border border-base-300">
          <h1 className="text-3xl md:text-4xl font-bold text-primary mb-2">Terms of Service</h1>
          <p className="text-base-content/60 mb-8">Last updated: July 2025</p>

          <section className="space-y-6 text-base-content/80 leading-relaxed">
            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">1. Acceptance of Terms</h2>
              <p>
                By accessing or using Smart Music Lab (&quot;we,&quot; &quot;our,&quot; or &quot;Smart Music Lab&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">2. Service Description</h2>
              <p>
                Smart Music Lab provides an AI-powered song generation service that creates personalized music based on user-provided descriptions. Our service transforms your ideas into unique, original songs.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">3. User Accounts & Eligibility</h2>
              <p>
                You must be at least 13 years old to use this service. By using our service, you represent and warrant that:
              </p>
              <ul className="list-disc list-inside mt-2 space-y-1">
                <li>You have the right to use this service</li>
                <li>You will provide accurate and complete information</li>
                <li>You will comply with all applicable laws and regulations</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">4. Subscriptions & Payments</h2>
              <p>
                Our service is offered on a per-purchase basis. Each song generation is a separate purchase. Prices are listed on our website and may be updated at any time. Payments are processed through secure third-party payment providers (PayPal, Stripe, Paddle). All payments are final and non-refundable except as stated in our Refund Policy.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">5. Acceptable Use</h2>
              <p>You agree not to use our service to:</p>
              <ul className="list-disc list-inside mt-2 space-y-1">
                <li>Generate content that infringes on intellectual property rights</li>
                <li>Create offensive, discriminatory, or unlawful content</li>
                <li>Reverse-engineer, decompile, or disassemble our service</li>
                <li>Use the service for spam or malicious purposes</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">6. Intellectual Property</h2>
              <p>
                The songs generated by our service are original works created through AI. Upon purchase, you receive a personal, non-exclusive, non-transferable license to use the generated song. You may use the song for personal, non-commercial purposes. Commercial redistribution or resale is prohibited.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">7. Service Availability</h2>
              <p>
                We strive to maintain uninterrupted service, but we do not guarantee that our service will be available at all times. We reserve the right to modify, suspend, or discontinue any aspect of our service at any time.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">8. Limitation of Liability</h2>
              <p>
                Our service is provided &quot;as is&quot; without warranties of any kind. We shall not be liable for any indirect, incidental, special, or consequential damages arising from the use of our service.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">9. Changes to Terms</h2>
              <p>
                We may update these Terms of Service from time to time. Changes will be effective upon posting on our website. Your continued use of our service after changes constitutes acceptance of the revised terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">10. Contact Information</h2>
              <p>
                If you have any questions about these Terms of Service, please contact us at{' '}
                <a href="mailto:support@smartmusiclab.com" className="text-primary hover:underline">support@smartmusiclab.com</a>
              </p>
            </div>
          </section>

          <hr className="my-8 border-base-300" />

          <h1 className="text-3xl md:text-4xl font-bold text-primary mb-2">服务条款</h1>
          <p className="text-base-content/60 mb-8">最后更新：2025年7月</p>

          <section className="space-y-6 text-base-content/80 leading-relaxed">
            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">一、接受条款</h2>
              <p>
                访问或使用 Smart Music Lab（以下简称&quot;我们&quot;或&quot;Smart Music Lab&quot;）即表示您同意受本服务条款约束。如您不同意本条款，请不要使用我们的服务。
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">二、服务描述</h2>
              <p>
                Smart Music Lab 提供 AI 驱动的歌曲生成服务，根据用户提供的描述创作个性化音乐。我们的服务将您的创意转化为独一无二的原创歌曲。
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">三、账户与资格</h2>
              <p>
                您必须年满 13 岁才能使用本服务。使用本服务即表示您保证：
              </p>
              <ul className="list-disc list-inside mt-2 space-y-1">
                <li>您有权使用本服务</li>
                <li>您将提供准确完整的信息</li>
                <li>您将遵守所有适用的法律法规</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">四、订阅与付款</h2>
              <p>
                本服务按次购买提供。每次歌曲生成为独立的购买。价格在网站上列出，可能随时更新。付款通过安全的第三方支付提供商（PayPal、Stripe、Paddle）处理。除退款政策另有规定外，所有付款均为最终付款，不予退还。
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">五、合理使用</h2>
              <p>您同意不将本服务用于：</p>
              <ul className="list-disc list-inside mt-2 space-y-1">
                <li>生成侵犯知识产权的内容</li>
                <li>创建攻击性、歧视性或非法内容</li>
                <li>对服务进行逆向工程、反编译或反汇编</li>
                <li>将服务用于垃圾邮件或恶意目的</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">六、知识产权</h2>
              <p>
                我们服务生成的歌曲是通过 AI 创建的原创作品。购买后，您获得个人、非排他、不可转让的使用许可。您可将歌曲用于个人非商业用途。禁止商业性再分发或转售。
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">七、服务可用性</h2>
              <p>
                我们努力保持服务不间断运行，但不保证服务在所有时间均可用。我们保留随时修改、暂停或终止服务任何方面的权利。
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">八、责任限制</h2>
              <p>
                本服务按&quot;现状&quot;提供，不作任何形式的保证。因使用本服务产生的任何间接、附带、特殊或后果性损失，我们不承担责任。
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">九、条款变更</h2>
              <p>
                我们可能不时更新本服务条款。变更将在网站发布时生效。变更后继续使用服务即表示接受修订后的条款。
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-base-content mb-2">十、联系方式</h2>
              <p>
                如您对本服务条款有任何疑问，请通过{' '}
                <a href="mailto:support@smartmusiclab.com" className="text-primary hover:underline">support@smartmusiclab.com</a> 联系我们
              </p>
            </div>
          </section>

          <div className="mt-10 pt-8 border-t border-base-300 text-center">
            <a href="/" className="text-primary hover:underline">← Back to Home / 返回首页</a>
          </div>
        </div>
      </div>
    </div>
  );
}
